//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class emlakDBEntities : DbContext
    {
        public emlakDBEntities()
            : base("name=emlakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ayarlar> ayarlar { get; set; }
        public virtual DbSet<Home2> Home2 { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<View_ilceler_LIST> View_ilceler_LIST { get; set; }
        public virtual DbSet<View_iller_LIST> View_iller_LIST { get; set; }
        public virtual DbSet<View_Personel_LIST> View_Personel_LIST { get; set; }
        public virtual DbSet<HomeDetails> HomeDetails { get; set; }
        public virtual DbSet<View_HomeDetails_LIST> View_HomeDetails_LIST { get; set; }
        public virtual DbSet<View_Musteri_LIST> View_Musteri_LIST { get; set; }
        public virtual DbSet<View_Home2_LIST> View_Home2_LIST { get; set; }
        public virtual DbSet<View_Home2Kiralik_LIST> View_Home2Kiralik_LIST { get; set; }
        public virtual DbSet<View_Home2Satilik_LIST> View_Home2Satilik_LIST { get; set; }
    }
}
