//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home2
    {
        public int EvID { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public Nullable<int> KatNumarasi { get; set; }
        public Nullable<int> ToplamEvAlani { get; set; }
        public Nullable<System.DateTime> YapimTarihi { get; set; }
        public string EvDurumu { get; set; }
        public Nullable<int> ilce_ID { get; set; }
        public Nullable<int> il_ID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<byte> IS_FLAG { get; set; }
        public Nullable<decimal> Depozito { get; set; }
        public Nullable<decimal> Kapora { get; set; }
        public string Sözleşme { get; set; }
        public Nullable<decimal> Caymabedeli { get; set; }
        public string Evresim { get; set; }
    }
}
