//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int MusteriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> EvID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<byte> IS_FLAG { get; set; }
        public string TelefonNO { get; set; }
    }
}
