//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ilceler_LIST
    {
        public int ilce_ID { get; set; }
        public string ilce_isim { get; set; }
        public Nullable<int> il_ID { get; set; }
    }
}
