//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HomeDetails_LIST
    {
        public int HomedetailsID { get; set; }
        public int EvID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string Notes { get; set; }
    }
}
