//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Musteri_LIST
    {
        public int MusteriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int EvID { get; set; }
        public string TelefonNO { get; set; }
        public string Evresim { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Kapora { get; set; }
        public Nullable<decimal> Depozito { get; set; }
    }
}
