//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakDB.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Home2Kiralik_LIST
    {
        public int EvID { get; set; }
        public string EvDurumu { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public Nullable<int> KatNumarasi { get; set; }
        public Nullable<int> ToplamEvAlani { get; set; }
        public Nullable<System.DateTime> YapimTarihi { get; set; }
        public string il_isim { get; set; }
        public string ilce_isim { get; set; }
        public string Notes { get; set; }
        public string Evresim { get; set; }
    }
}
